### ISSUE TITLE
Section-level map interactions

### ISSUE THREAD

**Issue by davidmcclure** [sul-cidr/graves-ui#12]
- At the start, the geo-anchored sections are grayed out with a low opacity.
- When the cursor hovers on a section, it pops up to a higher opacity and a "click to zoom" tooltip is displayed to the right of the heading.
- On click, the map focuses on the section anchor, the section text comes up to full opacity, and the map pin icon gets a border to indicate that the section has been visited.

**Comment by davidmcclure** [comment]
Actually, let's try this, which I think might stick closer to the principle of least surprise:
- When the cursor hovers on a section, check to see if the map is more or less "centered" on the region, by some kind of simple heuristic.
- If it is, do nothing.
- If not, `cursor: pointer` on the section, and place a little tooltip to the right of the text container, horizontally level with the cursor, that says "Click to focus on X". To the right of the tooltip, render a line to the section box on the map, like the span -> map lines.
- On click, pan the map to the section, and remove the tooltip / line.

**Comment by kgeographer** [comment]
I like that ­ or maybe even a little map icon with or without an arrow

kg
